name: infra-apply

on:
  push:
    branches:
      - main
    paths:
      - 'infra/**'

jobs:
  apply:
    runs-on: ubuntu-latest
    environment:
      name: prod
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform init
        run: terraform init
        working-directory: infra/envs/prod

      - name: Terraform apply
        run: terraform apply -auto-approve
        working-directory: infra/envs/prod
